# Generated by Django 3.2.5 on 2023-08-12 18:04

from django.db import migrations, models

import random
import string
from datetime import datetime, timedelta


def create_initial_data(apps, schema_editor):
    MeasurementModel = apps.get_model('core', 'MeasurementModel')

    def generate_random_string(length):
        characters = string.ascii_letters + string.digits
        return ''.join(random.choice(characters) for _ in range(length))

    def generate_random_datetime():
        start_date = datetime(2000, 1, 1)
        end_date = datetime(2023, 12, 31)
        delta = end_date - start_date
        random_days = random.randint(0, delta.days)
        return start_date + timedelta(days=random_days)

    data_list = []
    for _ in range(1000):
        item = {
            "name": "Species " + generate_random_string(5),
            "data": generate_random_string(255),
            "start_at": generate_random_datetime(),
            "end_at": generate_random_datetime()
        }
        data_list.append(item)

    # Create rows/records
    new_items = [MeasurementModel(**d) for d in data_list]
    MeasurementModel.objects.bulk_create(new_items)




class Migration(migrations.Migration):

    initial = True

    dependencies = [ ('core', '0001_initial'),
    ]

    operations = [
       migrations.RunPython(create_initial_data, create_initial_data),
    ]
